import { loadNative } from "./loader-state.js";

/**
 * Native addon entrypoint.
 *
 * Hand-written surface area: one `loadNative()` call. Everything else in
 * this file (the surface-area `export const` block between MARKER_START
 * and MARKER_END) is rewritten by `packages/natives/scripts/gen-enums.ts`
 * after `napi build` regenerates `index.d.ts`.
 *
 * Loader logic lives in `./loader-state.js` so the pure helpers stay
 * unit-testable without triggering AVX2 detection or filesystem probes on
 * import. Types are auto-generated by napi-rs in `./index.d.ts`.
 */

/**
 * Lazily load the native addon. Importing this module must NOT trigger the
 * `.node` load (AVX2 detection / filesystem probes) — only the first call to a
 * native binding does. The `/desktop` and `/clipboard` subpaths already follow
 * this contract; the main entrypoint now matches so that importing the index
 * (e.g. from the CLI entrypoint) stays addon-free until a binding is actually
 * used. The generated `export const X = nativeBindings.X` below captures a
 * wrapper, not the live binding, so no addon loads at module-eval time.
 */
/**
 * Lazily load the native addon. Importing this module must NOT trigger the
 * `.node` load (AVX2 detection / filesystem probes) - only the first call to a
 * native binding does. The `/desktop` and `/clipboard` subpaths already follow
 * this contract; the main entrypoint now matches so that importing the index
 * (e.g. from the CLI entrypoint) stays addon-free until a binding is actually
 * used. The generated `export const X = nativeBindings.X` below captures a
 * wrapper, not the live binding, so no addon loads at module-eval time.
 */
const nativeBindings = (() => {
	let loaded = null;
	// Capture the host platform at module-eval time. Some consumers (notably the
	// TUI test-suite) override `process.platform` to simulate other OSes; if the
	// addon loaded on first use, it would resolve for the overridden platform
	// (e.g. `win32-x64`) and fail on a host that only has its own addon built.
	// Loading for the real host platform keeps behaviour identical to eager eval
	// while still deferring the `.node` load until a binding is actually used.
	const hostPlatform = process.platform;
	const get = () => (loaded ??= loadNative(hostPlatform));
	return new Proxy(
		{},
		{
			get(_target, prop) {
				// `prop` is the native member name (e.g. "grep", "DesktopSession").
				// Return a lazy stand-in that defers the addon load until first real
				// use: a call, a `new`, or any property access (`.prototype`,
				// `instanceof`, statics, symbols). Importing the index only builds
				// these stand-ins, so no addon loads at module-eval time.
				//
				// napi bindings are not regular JS functions, so they are invoked
				// directly (not via Function.prototype.apply) and constructed with
				// `Reflect.construct(..., newTarget)` - `newTarget` is this wrapper,
				// which keeps `new.target` and `instanceof` consistent with the
				// exported (wrapped) constructor.
				const applyTrap = (_t, _thisArg, args) => get()[prop](...args);
				const constructTrap = (_t, args, newTarget) =>
					Reflect.construct(get()[prop], args, newTarget);
				const wrapperGet = (_w, p) => get()[prop][p];
				const wrapperProto = () => Object.getPrototypeOf(get()[prop]);
				return new Proxy(
					function () {},
					{
						apply: applyTrap,
						construct: constructTrap,
						get: wrapperGet,
						getPrototypeOf: wrapperProto,
					},
				);
			},
		},
	);
})();
// --- generated native exports (do not edit) ---
// classes
export const AudioCapture = nativeBindings.AudioCapture;
export const AudioPlayback = nativeBindings.AudioPlayback;
export const DesktopSession = nativeBindings.DesktopSession;
export const FileLock = nativeBindings.FileLock;
export const LiveWebRtcPeer = nativeBindings.LiveWebRtcPeer;
export const MacAppearanceObserver = nativeBindings.MacAppearanceObserver;
export const MacOSPowerAssertion = nativeBindings.MacOSPowerAssertion;
export const Process = nativeBindings.Process;
export const PtySession = nativeBindings.PtySession;
export const Shell = nativeBindings.Shell;

// functions
export const __ompInstallTokioRuntime = nativeBindings.__ompInstallTokioRuntime;
export const __piNativesV17_5_3 = nativeBindings.__piNativesV17_5_3;
export const astEdit = nativeBindings.astEdit;
export const astGrep = nativeBindings.astGrep;
export const astMatch = nativeBindings.astMatch;
export const blockRangeAt = nativeBindings.blockRangeAt;
export const copyToClipboard = nativeBindings.copyToClipboard;
export const cosineSimilarityPairs = nativeBindings.cosineSimilarityPairs;
export const countTokens = nativeBindings.countTokens;
export const detectMacOSAppearance = nativeBindings.detectMacOSAppearance;
export const deviceCheckGenerateToken = nativeBindings.deviceCheckGenerateToken;
export const diffLineRuns = nativeBindings.diffLineRuns;
export const diffLines = nativeBindings.diffLines;
export const diffWords = nativeBindings.diffWords;
export const enclosingBlockBoundaries = nativeBindings.enclosingBlockBoundaries;
export const encodeSixel = nativeBindings.encodeSixel;
export const executeShell = nativeBindings.executeShell;
export const extractSegments = nativeBindings.extractSegments;
export const fuzzyFind = nativeBindings.fuzzyFind;
export const getSupportedLanguages = nativeBindings.getSupportedLanguages;
export const getWorkProfile = nativeBindings.getWorkProfile;
export const glob = nativeBindings.glob;
export const grep = nativeBindings.grep;
export const hasMatch = nativeBindings.hasMatch;
export const highlightCode = nativeBindings.highlightCode;
export const htmlToMarkdown = nativeBindings.htmlToMarkdown;
export const invalidateFsScanCache = nativeBindings.invalidateFsScanCache;
export const isoBackend = nativeBindings.isoBackend;
export const isoDiff = nativeBindings.isoDiff;
export const isoIsUnavailableError = nativeBindings.isoIsUnavailableError;
export const isoProbe = nativeBindings.isoProbe;
export const isoResolve = nativeBindings.isoResolve;
export const isoStart = nativeBindings.isoStart;
export const isoStop = nativeBindings.isoStop;
export const listWorkspace = nativeBindings.listWorkspace;
export const matchesKey = nativeBindings.matchesKey;
export const matchesKittySequence = nativeBindings.matchesKittySequence;
export const matchesLegacySequence = nativeBindings.matchesLegacySequence;
export const mmrRerankIndices = nativeBindings.mmrRerankIndices;
export const parseKey = nativeBindings.parseKey;
export const parseKittySequence = nativeBindings.parseKittySequence;
export const pdfToMarkdown = nativeBindings.pdfToMarkdown;
export const readImageFromClipboard = nativeBindings.readImageFromClipboard;
export const renderSnapcompactPng = nativeBindings.renderSnapcompactPng;
export const search = nativeBindings.search;
export const setHangulCompatJamoWidthOverride = nativeBindings.setHangulCompatJamoWidthOverride;
export const sliceWithWidth = nativeBindings.sliceWithWidth;
export const snapcompactSupportedChars = nativeBindings.snapcompactSupportedChars;
export const structuredPatchHunks = nativeBindings.structuredPatchHunks;
export const summarizeCode = nativeBindings.summarizeCode;
export const supportsLanguage = nativeBindings.supportsLanguage;
export const truncateToWidth = nativeBindings.truncateToWidth;
export const vectorIndexTopK = nativeBindings.vectorIndexTopK;
export const visibleWidth = nativeBindings.visibleWidth;
export const wrapTextWithAnsi = nativeBindings.wrapTextWithAnsi;

// string/numeric enums (napi-rs string_enum produces TS-only const enum)
export const AstMatchStrictness = {
	Cst: "cst",
	Smart: "smart",
	Ast: "ast",
	Relaxed: "relaxed",
	Signature: "signature",
	Template: "template",
};
export const Ellipsis = {
	Unicode: 0,
	Ascii: 1,
	Omit: 2,
};
export const Encoding = {
	O200kBase: "O200kBase",
	Cl100kBase: "Cl100kBase",
};
export const FileType = {
	File: 1,
	Dir: 2,
	Symlink: 3,
};
export const GrepOutputMode = {
	Content: "content",
	Count: "count",
	FilesWithMatches: "filesWithMatches",
};
export const IsoBackendKind = {
	Apfs: 0,
	Btrfs: 1,
	Zfs: 2,
	LinuxReflink: 3,
	Overlayfs: 4,
	WindowsBlockClone: 5,
	Projfs: 6,
	Rcopy: 7,
};
export const IsoChangeKind = {
	Added: 0,
	Modified: 1,
	Removed: 2,
};
export const KeyEventType = {
	Press: 1,
	Repeat: 2,
	Release: 3,
};
export const MacOSAppearance = {
	Dark: "dark",
	Light: "light",
};
export const ProcessStatus = {
	Running: "running",
	Exited: "exited",
};
// --- end generated native exports ---
